### PR TITLE
New home

### PR DESCRIPTION
**Pull request by adriana-arenivar**
Implementation of home page, with banner, About Us section that includes learn more button that leads to About Us, and includes a Youtube Video that automatically plays upon landing on page. Also includes sponsors, limit of 3 shown

Packages installed: npm install @angular/youtube-player

Changes to assets file: added image folder that contains logo icons, and banner picture

### CODE REVIEW

**Review by Ry-ka — CHANGES_REQUESTED** [review]
wrong destination branch

**Comment by adriana-arenivar** [comment]
change destination branch :)

**Comment by adriana-arenivar** [comment]
Font size changed

**Review by Ry-ka — CHANGES_REQUESTED** [review]
Can you change the source image of the sponsors that you have to the same one that the sponsors page already uses? So that we don't have duplicate images

**Comment by Ry-ka** [comment]
Also, I wasn't talking about the font size, but rather the ratio between the dog picture and the about us banner. About us is too thin, it looks like the youtube video is cut in half.

**Comment by adriana-arenivar** [comment]
Source of photos is from sponsors, space between About Us and banner is larger.

**Review by BarrakBM — APPROVED** [review]
LGTM!

**Review by Ry-ka — APPROVED** [review]

**Pull request merged**
